services:
  - type: web
    name: financeiro-af360bank
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -e .
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: AUTH_SERVER_URL
        value: https://af360bank.onrender.com
      - key: APP_NAME
        value: financeiro
      - key: SECRET_KEY
        value: your-secret-key-here
